# Change these first
owner: TheCrafters001 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Website
    url: https://thecrafters001.github.io
  - name: TF2 Server
    check: "tcp-ping"
    url: $TF2_SERVER
    port: $PORT
    icon: https://steamcdn-a.akamaihd.net/apps/tf2/blog/images/favicon.ico

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /status
  logoUrl: https://thecrafters001.github.io/assets/TC001Logo_NoBack.png
  name: Upptime
  introTitle: "**Server Uptime**"
  introMessage: This contains the **real-time** server data for my website and TF2 Server. This utilizes just GitHub Actions, Issues, and Pages.
  navbar:
    - title: Status
      href: /
    - title: Support
      href: https://tf2-gj-server.tawk.help/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
